# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '13.2'
target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App

  # Major pods
  pod 'Charts'
  pod 'R.swift'
  pod 'JTAppleCalendar'
  pod 'XJYChart', '2.5.0'
  pod "NumericPicker"
  pod 'DHSmartScreenshot', '1.3.1'

  # MS Apps related Pods
  pod 'AppCenter'
  pod 'AppCenter/Distribute'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end